desktopFileName="Designer-${WEBMETHODS_VERSION}"
desktopFileComment="Software AG Designer ${WEBMETHODS_VERSION}"
desktopFileFileName="SAG-Designer-${WEBMETHODS_VERSION}.desktop"
desktopFileExecutable="${wm_home_dir}/Designer/eclipse/eclipse"
desktopFileIcon="${wm_home_dir}/Designer/eclipse/icon.xpm"
