#######################################################################################################
#
# DO NOT EDIT THIS FILE!
#
# Instead, create a file settings-local.sh, and set your variasbles there.
# For example, rather than adjusting EMPOWER_PASSWORD here, copy the variable
# definition to settings-local.sh, and adjust trhe value there.
#
# Keep in mind, that the syntax rules of a Bash script apply here. In other words, the
# backslash is the escape character for certain other characters. For example, use
# \\, rather than \.
#
# It is typically sufficient, to copy the following variables to settings-local.sh,
# and edit the file.
#   WEBMETHODS_PRODUCT
#   WEBMETHODS_VERSION
#   LICENSE_FILE_IS
#   LICENSE_FILE_UM
#   LICENSE_FILE_TS
#   EMPOWER_USERID
#   EMPOWER_PASSWORD
#   ADMIN_PASSWORD
#   SUDO_PASSWORD
# All other variables should be fine, as they are.
#

# webMethods product, which is being installed. Identifies a subdirectory of "products". As of this
# writing, valid products are "wmSuite" (default), and Tamino
WEBMETHODS_PRODUCT=wmSuite
# webMethods version, which is being installed. As of this writing, supported versions are 10.5, 10.7,
# 10.11, and 10.15
WEBMETHODS_VERSION=10.5
# Target installation directory. We recommend not to change this.
WEBMETHODS_HOME_DIR="/opt/wm/${WEBMETHODS_VERSION}"
# Temporary directory for installation files
WEBMETHODS_INSTALLATION_FILES_DIR="/opt/wm/installation"

# License file locations; required icense files are IS (Integration Server), UM (Universal Messaging),
# and TS (webMethods test suite)
LICENSE_FILE_IS="/tmp/wm-inst/is-license.xml"
LICENSE_FILE_UM="/tmp/wm-inst/um-license.xml"
LICENSE_FILE_TS="/tmp/wm-inst/ts-license.xml"

# Empower user name, and password, for software download
EMPOWER_USERID="your.email.address@your.employer"
EMPOWER_PASSWORD="ReplaceMeWithTheRealPassword"

# User name of the "sag" user. Servers will be running under this user id.
ADMIN_USERID="sag"
# Primary group of the admin user. Servers will be using this as the primary group id.
ADMIN_GROUPID="sag"
# Password of the "sag" user, for use with "sudo".
ADMIN_PASSWORD="manage"

# SAG Installer URL. Leave this, as it is, unless you need a different webMethods version
SAG_INSTALLER_VERSION="20221103"
SAG_INSTALLER_URL="https://empowersdc.softwareag.com/ccinstallers/SoftwareAGInstaller${SAG_INSTALLER_VERSION}-Linux_x86_64.bin"
